### PR TITLE
Adding first snippets of documentation

### PR DESCRIPTION
**Pull request by jsanemet**
Documenting symbols under the 'pkg' directory as a way of try out the documentation system for GoLang.

### CODE REVIEW

**Comment by jsanemet** [comment]
You can visualize this documentation with the use of godoc: https://pkg.go.dev/golang.org/x/tools/cmd/godoc

**Comment by jsanemet** [comment]
Guidelines on how these are written are here:
https://go.dev/doc/comment

**Review by adrianfusco — APPROVED** [review]
Following this https://go.dev/blog/godoc it seems to be okay. 

It would be nice if we post a screenshot of the result of the `godoc --http=...` web doc result at some point. Something like this: https://www.linkedin.com/pulse/how-generate-documentation-from-code-golang-alex-guidi

**Comment by jsanemet** [comment]
@adrianfusco Godoc works a little different. It does not export the documentation as static HTML like many others, but instead runs a live server, letting you see it by going into localhost. The idea is that you can keep working and the server will update itself with any changes.

**Comment by jsanemet** [comment]
@adrianfusco In the end it looks something like this:
image

**Review by IgnacioPro — APPROVED** [review]
Thank you, very comprehensive.

**Pull request merged**
