### PR TITLE
Setting up logging on the project

### PR DESCRIPTION
**Pull request by jsanemet**
On the PR:
    - Installed Logrus as the logging framework.
    - Before any CLI command is run, the log is configured to react to the '-d' flag.
    - Extracted each argument used by the CLI as a string constant.
    - Left some log lines on the 'command' for the '-d' flag to be tried out.

### CODE REVIEW

**Review by adrianfusco — COMMENTED** [review]
If you want we can discuss it also in the meeting keeping in mind we'll also discuss about `cobra` framework. But, from my side this is okay.

Let's consider the following based on https://pkg.go.dev/github.com/sirupsen/logrus#section-readme:
```
Logrus is in maintenance-mode. We will not be introducing new features. It's simply too hard to do in a way that won't break many people's projects, which is the last thing you want from your Logging library (again...).

This does not mean Logrus is dead. Logrus will continue to be maintained for security, (backwards compatible) bug fixes, and performance (where we are limited by the interface
```
And I just have one non important doubt, is it well indented? I see so much distance in each indentation.

**Comment by jsanemet** [comment]
> If you want we can discuss it also in the meeting keeping in mind we'll also discuss about `cobra` framework. But, from my side this is okay.
> 
> Let's consider the following based on https://pkg.go.dev/github.com/sirupsen/logrus#section-readme:
> 
> ```
> Logrus is in maintenance-mode. We will not be introducing new features. It's simply too hard to do in a way that won't break many people's projects, which is the last thing you want from your Logging library (again...).
> 
> This does not mean Logrus is dead. Logrus will continue to be maintained for security, (backwards compatible) bug fixes, and performance (where we are limited by the interface
> ```
> 
> And I just have one non important doubt, is it well indented? I see so much distance in each indentation.

I believe that the logging format is configurable, so we can set it up how we would like it best. Regarding maintenance mode, I do not believe that is much of a problem. It just means that the project is finished, so we could expect it to be its most stable. I do not think we need that much out of a logging library either, others will do just fine too.

**Review by adrianfusco — DISMISSED** [review]
From my side then +1. Thank you, Jorge.

**Review by IgnacioPro — DISMISSED** [review]
+1

**Review by IgnacioPro — APPROVED** [review]
+1 looks good.

**Review by adrianfusco — APPROVED** [review]
From my side +1. Thanks Jorge!

**Pull request merged**
