### PR TITLE
Defining CLI for adhoc mode

### PR DESCRIPTION
**Pull request by jsanemet**
I have chosen the Cobra framework to deal with the CLI side of Syncron. This one seems to be pretty standard for GoLang and is comfortable to use.

Through it, I have described the CLI for Adhoc mode following the same arguments as we had on UpGet. Here is an example of how it looks like:
`syncron download all --months 1`

If you want to try for yourself, run:
`go run cmd/adhoc/main.go`

### CODE REVIEW

**Comment by jsanemet** [comment]
This will be helpful to understand the arrangement of the code:
https://github.com/spf13/cobra/blob/main/user_guide.md

**Comment by adrianfusco** [comment]
Should it return any output?

```
[2022-09-20 14:02:21] {afuscoar@afuscoar} (~/.Redhat/Projects/github/syncron) (main)$ -> go run cmd/adhoc/main.go 
[2022-09-20 14:02:21] {afuscoar@afuscoar} (~/.Redhat/Projects/github/syncron) (main)$ -> 
```

**Comment by IgnacioPro** [comment]
> Should it return any output?
> 
> ```
> [2022-09-20 14:02:21] {afuscoar@afuscoar} (~/.Redhat/Projects/github/syncron) (main)$ -> go run cmd/adhoc/main.go 
> [2022-09-20 14:02:21] {afuscoar@afuscoar} (~/.Redhat/Projects/github/syncron) (main)$ -> 
> ```

No, since there is nothing on the file, just an empty func.

**Comment by jsanemet** [comment]
@adrianfusco Nothing yet. This PR is only meant to give an outline of the CLI. No contents as of now.

**Review by adrianfusco — APPROVED** [review]

**Comment by adrianfusco** [comment]
> > Should it return any output?
> > ```
> > [2022-09-20 14:02:21] {afuscoar@afuscoar} (~/.Redhat/Projects/github/syncron) (main)$ -> go run cmd/adhoc/main.go 
> > [2022-09-20 14:02:21] {afuscoar@afuscoar} (~/.Redhat/Projects/github/syncron) (main)$ -> 
> > ```
> 
> No, since there is nothing on the file, just an empty func.

I didn't mean because the function content, I meant because the description of the PR. Jorge clarified now. Thanks.

**Comment by IgnacioPro** [comment]
As a side note, I think it is worth discussing the choosing of cli framework moving forward, as this is an important characteristic that will impact furutre development. What do you think @jsanemet

**Review by JoseSilvaHermida — APPROVED** [review]
I did not know about the cobra framework, but it looks very powerful.

Nice addition.

**Comment by jsanemet** [comment]
@IgnacioPro Sure, we can have a talk about it.

**Review by IgnacioPro — APPROVED** [review]
Looks good, we have gone over it together in meeting.
Thank you +1

**Pull request merged**
