### PR TITLE
Setting the ground for the project

### PR DESCRIPTION
**Pull request by jsanemet**
In here:
  - Defined the GO module for the project.
  - Add VSCode to .gitignore.
  - Adding a hello world to have something to compile.

### CODE REVIEW

**Review by bregman-arie — APPROVED** [review]
Small, clear, concise, ... 100%
Not sure why specifically 1.17 and not 1.18 but let me know.

As I said on the kickoff, let's make sure everyone on the effort approves it. Sorry for the slow process, but that's how we'll roll at least at the beginning

**Comment by IgnacioPro** [comment]
Thank you Jorge and congrats, you are the lucky winner of the first PR for syncron :D
@bregman-arie, as we discussed on Slack, we are still undecided on what version of Go to target.
By using version 17 for now, this will allow us to move to 18 quite easily if we decide to do so.
This will be discussed on out next sync.

**Review by IgnacioPro — APPROVED** [review]
Looks good. +2

**Comment by bregman-arie** [comment]
Let's merge once @adrianfusco approves

**Review by JoseSilvaHermida — APPROVED** [review]
Nice

**Review by adrianfusco — APPROVED** [review]
+1

**Comment by bregman-arie** [comment]
> Nice

Nice but not vote? :)

**Pull request merged**
