### PR TITLE
Adding entrypoint for adhoc mode

### PR DESCRIPTION
**Pull request by jsanemet**
Restructured cmd/ folder to accomodate to two different entry points: adhoc and server.

Updated github workflow to reflect such thing.

### CODE REVIEW

**Review by bregman-arie — APPROVED** [review]
Looks good

**Comment by adrianfusco** [comment]
Why `adhoc`, purpose on it? Just to know why this is restructured like this.

**Comment by bregman-arie** [comment]
> Why `adhoc`, purpose on it? Just to know why this is restructured like this.

Do you mean what's the purpose of adhoc?
It can be executed in two ways:
server: syncron-server (a daemon running hte background which downloads and removes files periodically)
adhoc: syncron (CLI adhoc command for downloading files on demand)

**Comment by adrianfusco** [comment]
> > Why `adhoc`, purpose on it? Just to know why this is restructured like this.
> 
> Do you mean what's the purpose of adhoc? It can be executed in two ways: server: syncron-server (a daemon running hte background which downloads and removes files periodically) adhoc: syncron (CLI adhoc command for downloading files on demand)

Thanks for the explanation.

**Review by adrianfusco — APPROVED** [review]
+1

**Review by IgnacioPro — APPROVED** [review]
Looks good !

**Pull request merged**
